version: 2

references:
  defaults: &defaults
    machine:
      enabled: true

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

jobs:
  test:
    docker:
      - image: caronae/php:latest
        environment:
          APP_ENV: testing
      - image: postgres:9.6-alpine
        environment:
          POSTGRES_USER: caronae
          POSTGRES_DB: caronae_testing
    steps:
      - *restore_repo
      - checkout
      - run:
          name: Persist build number
          command: ./scripts/calcrev.sh > build_number.txt
      - run:
          name: Install dependencies
          command: composer install --no-interaction --no-ansi
      - save_cache:
          key: composer-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run:
          name: Run tests
          command: |
            mkdir -p ~/phpunit
            ./vendor/bin/phpunit --debug --log-junit ~/phpunit/junit.xml
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - *restore_repo
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: export TAG=$(cat build_number.txt)
      - run:
          name: Build backend
          command: |
            docker build -t caronae/backend:$TAG -f Dockerfile.app ..
            docker push caronae/backend:$TAG
      - run:
          name: Build backend-worker
          command: |
            docker build -t caronae/backend-worker:$TAG -f Dockerfile.worker --build-arg BACKEND_TAG=$TAG .
            docker push caronae/backend-worker:$TAG

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: circleci-workflow
      - build:
          requires:
            - test

