version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node
        environment:
          APP_ENV: testing
          APP_DEBUG: true
          APP_KEY: kjcndjjksddwdwdw
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_DATABASE: circle_test
          DB_USERNAME: root
      - image: postgres:9.4.11
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    working_directory: ~/caronae

    steps:
      - run:
          name: Install System Packages
          command: sudo apt-get update && sudo apt-get -y install git unzip zlib1g-dev libpq-dev
      - checkout
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install pdo pdo_pgsql zip pgsql
      - run:
          name: Install Composer
          command: 'curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer'
      - restore_cache:
          key: composer-{{ checksum "composer.json" }}
      - run: composer install --no-interaction --no-ansi
      - save_cache:
          key: composer-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run:
          name: Initialize Database
          command: php artisan migrate:refresh
      - run:
          name: Run Tests
          command: './vendor/bin/phpunit --log-junit $CIRCLE_TEST_REPORTS/phpunit/junit.xml'