version: '2'

services:
  caronae-backend:
    container_name: caronae-backend
    image: caronae/backend
    depends_on:
      - postgres
    volumes:
      - ../:/var/www
      - $CIRCLE_TEST_REPORTS:/var/www/reports
    environment:
      - TESTING_DB_HOST=postgres
    command: ./vendor/bin/phpunit --debug --log-junit reports/phpunit/junit.xml

  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=caronae
      - POSTGRES_DB=caronae_testing
